export const items = [
  {
    id: 1,
    name: "Paneer Butter Masala",
    price: "₹200",
    imageName: "pbm.jpeg",
    category: ["vegetarian"],
    type: "Main Dish",
    desc: "A classic Indian dish made with locally sourced paneer, butter, and spices. Pair it with naan or roti for a quick and easy meal.",
  },
  {
    id: 2,
    name: "ChocolateCake",
    price: "₹150",
    imageName: "ChocolateCake.jpeg",
    category: ["vegetarian"],
    type: "Desserts",
    desc: "A classic Indian dessert made with locally sourced milk, sugar, and cocoa powder. Pair it with brownies or cheesecakes for a healthy and delicious treat.",
  },
  {
    id: 3,
    name: "IceCream",
    price: "₹100",
    imageName: "iceCream.jpeg",
    category: ["vegetarian", "vegan"],
    type: "Desserts",
    desc: "A classic Indian ice cream made with locally sourced milk, sugar, and vanilla extract.",
  },
  {
    id: 4,
    imageName: "pannertikka.jpg",
    name: "PaneerTikka",
    price: "₹200",
    category: ["vegetarian"],
    type: "Snacks",
    desc: "A classic Indian dish made with locally sourced paneer, spices, and yogurt. Pair it with naan or roti for a quick and easy meal.",
  },
  {
    id: 5,
    imageName: "samosa.jpeg",
    name: "Samosa",
    price: "₹50",
    category: ["vegetarian", "vegan"],
    type: "Snacks",
    desc: "A classic Indian snack made with locally sourced potatoes, spices, and flour. Perfect as a quick bite.",
  },
  {
    id: 6,
    imageName: "masalaDosa.jpg",
    name: "Masala Dosa",
    price: "₹100",
    category: ["vegetarian", "vegan"],
    type: "Breakfast",
    desc: "A rice crepe stuffed with spiced potatoes, served with sambar and chutney.",
  },
  {
    id: 7,
    imageName: "IdliSambar.jpg",
    name: "Idli Sambar",
    price: "₹100",
    category: ["vegetarian", "vegan"],
    type: "Breakfast",
    desc: "A traditional South Indian breakfast dish of steamed rice cakes served with sambar.",
  },
  {
    id: 8,
    imageName: "prawn.jpg",
    name: "Prawn Masala",
    price: "₹200",
    category: ["Sea-Food"],
    type: "Main Dish",
    desc: "A classic Indian dish made with locally sourced prawns, spices, and yogurt. Pair it with naan or roti for a quick and easy meal.",
  },
  {
    id: 9,
    imageName: "fish.jpg",
    name: "Fish Fry",
    price: "₹200",
    category: ["Sea-Food"],
    type: "Main Dish",
    desc: "A crispy fried fish dish with a blend of spices. Perfect as a main course or starter.",
  },
  {
    id: 10,
    imageName: "ChickenRoast.jpeg",
    name: "Chicken Fry",
    price: "₹200",
    category: ["non-vegetarian"],
    type: "Main Dish",
    desc: "A classic Indian dish made with locally sourced chicken, spices, and yogurt. Pair it with naan or roti for a quick and easy meal.",
  },
  {
    id: 11,
    imageName: "lemonrice.jpg",
    name: "Lemon Rice",
    price: "₹90",
    category: ["vegetarian", "vegan"],
    type: "Main Dish",
    desc: "A tangy rice dish infused with lemon juice and spices. Great as a light meal.",
  },
  {
    id: 12,
    imageName: "Noodles.jpeg",
    name: "Noodles",
    price: "₹90",
    category: ["vegetarian"],
    type: "Snacks",
    desc: "A bowl of flavorful and tasty stir-fried noodles, perfect as a snack or meal.",
  },
  {
    id: 13,
    imageName: "Puttu.jpg",
    name: "Puttu",
    price: "₹90",
    category: ["vegetarian", "vegan"],
    type: "Breakfast",
    desc: "A traditional steamed rice cake, often served with curries or chutney.",
  },
  {
    id: 14,
    imageName: "pizzaStar.jpg",
    name: "PizzaStar",
    price: "₹200",
    category: ["vegetarian"],
    type: "Main Dish",
    desc: "A pizza topped with fresh vegetables and cheese. Perfect for sharing.",
  },
  {
    id: 15,
    imageName: "mutton.jpeg",
    name: "Mutton Chukka",
    price: "₹200",
    category: ["non-vegetarian"],
    type: "Main Dish",
    desc: "A spicy, flavorful mutton dish cooked with Indian spices. Great with rice or bread.",
  },
  {
    id: 16,
    imageName: "chai.jpg",
    name: "Chai",
    price: "₹20",
    category: ["vegetarian"],
    type: "Drinks",
    desc: "A refreshing drink made with tea leaves and milk, perfect for a mornings and evenings.",
  },
  {
    id: 17,
    imageName: "mangoJuice.jpg",
    name: "Mango Juice",
    price: "₹20",
    category: ["vegetarian"],
    type: "Drinks",
    desc: "A refreshing drink made with mangoes, perfect for a morning or evening.",
  },
  {
    id: 18,
    imageName: "guavaJuice.jpg",
    name: "Guava Juice",
    price: "₹20",
    category: ["vegetarian"],
    type: "Drinks",
    desc: "A refreshing drink made with guavas, perfect for a morning or evening.",
  },
  {
    id: 19,
    imageName: "chickenSoup.jpg",
    name: "Chicken Soup",
    price: "₹320",
    category: ["non-vegetarian"],
    type: "Drinks",
    desc: "A hearty soup made with chicken, perfect before a hearty meal.",
  },
  {
    id: 20,
    imageName: "muttonbone.jpg",
    name: "Mutton Bone Soup",
    price: "₹400",
    category: ["non-vegetarian"],
    type: "Drinks",
    desc: "A hearty soup made with mutton, perfect before a hearty meal.",
  },
];
