spring:
  jpa:
    hibernate:
      ddl-auto: updatechr
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5448/restaurant
    username: codeNaren
    password: password

server:
  error:
    include-message: always
  port: 8080


logging:
  level:
    sql: debug
    org:
      springframework:
        security: debug