export const items = [
  {
    id: 1,
    name: "Paneer Butter Masala",
    price: "₹200",
    imageName: "pbm.jpeg",
    category: ["vegetarian"],
    type: "Main Dish",
    desc: "A classic Indian dish made with locally sourced paneer, butter, and spices. Pair it with naan or roti for a quick and easy meal.",
  },
  {
    id: 2,
    name: "ChocolateCake",
    price: "₹150",
    imageName: "ChocolateCake.jpeg",
    category: ["vegetarian"],
    type: "Desserts",
    desc: "A classic Indian dessert made with locally sourced milk, sugar, and cocoa powder. Pair it with brownies or cheesecakes for a healthy and delicious treat.",
  },
  {
    id: 3,
    name: "IceCream",
    price: "₹100",
    imageName: "iceCream.jpeg",
    category: ["vegetarian", "vegan"],
    type: "Desserts",
    desc: "A classic Indian ice cream made with locally sourced milk, sugar, and vanilla extract.",
  },
  {
    id: 4,
    imageName: "pannertikka.jpg",
    name: "PaneerTikka",
    price: "₹200",
    category: ["vegetarian"],
    type: "Snacks",
    desc: "A classic Indian dish made with locally sourced paneer, spices, and yogurt. Pair it with naan or roti for a quick and easy meal.",
  },
  {
    id: 5,
    imageName: "samosa.jpeg",
    name: "Samosa",
    price: "₹50",
    category: ["vegetarian", "vegan"],
    type: "Snacks",
    desc: "A classic Indian snack made with locally sourced potatoes, spices, and flour. Perfect as a quick bite.",
  },
  {
    id: 6,
    imageName: "masalaDosa.jpg",
    name: "Masala Dosa",
    price: "₹100",
    category: ["vegetarian", "vegan"],
    type: "Breakfast",
    desc: "A rice crepe stuffed with spiced potatoes, served with sambar and chutney.",
  },
  {
    id: 7,
    imageName: "IdliSambar.jpg",
    name: "Idli Sambar",
    price: "₹100",
    category: ["vegetarian", "vegan"],
    type: "Breakfast",
    desc: "A traditional South Indian breakfast dish of steamed rice cakes served with sambar.",
  },
  {
    id: 8,
    imageName: "prawn.jpg",
    name: "Prawn Masala",
    price: "₹200",
    category: ["Sea-Food"],
    type: "Main Dish",
    desc: "A classic Indian dish made with locally sourced prawns, spices, and yogurt. Pair it with naan or roti for a quick and easy meal.",
  },
  {
    id: 9,
    imageName: "fish.jpg",
    name: "Fish Fry",
    price: "₹200",
    category: ["Sea-Food"],
    type: "Main Dish",
    desc: "A crispy fried fish dish with a blend of spices. Perfect as a main course or starter.",
  },
  {
    id: 10,
    imageName: "ChickenRoast.jpeg",
    name: "Chicken Fry",
    price: "₹200",
    category: ["non-vegetarian"],
    type: "Main Dish",
    desc: "A classic Indian dish made with locally sourced chicken, spices, and yogurt. Pair it with naan or roti for a quick and easy meal.",
  },
  {
    id: 11,
    imageName: "lemonrice.jpg",
    name: "Lemon Rice",
    price: "₹90",
    category: ["vegetarian", "vegan"],
    type: "Main Dish",
    desc: "A tangy rice dish infused with lemon juice and spices. Great as a light meal.",
  },
  {
    id: 12,
    imageName: "Noodles.jpeg",
    name: "Noodles",
    price: "₹90",
    category: ["vegetarian"],
    type: "Snacks",
    desc: "A bowl of flavorful and tasty stir-fried noodles, perfect as a snack or meal.",
  },
  {
    id: 13,
    imageName: "Puttu.jpg",
    name: "Puttu",
    price: "₹90",
    category: ["vegetarian", "vegan"],
    type: "Breakfast",
    desc: "A traditional steamed rice cake, often served with curries or chutney.",
  },
  {
    id: 14,
    imageName: "pizzaStar.jpg",
    name: "PizzaStar",
    price: "₹200",
    category: ["vegetarian"],
    type: "Main Dish",
    desc: "A pizza topped with fresh vegetables and cheese. Perfect for sharing.",
  },
  {
    id: 15,
    imageName: "mutton.jpeg",
    name: "Mutton Chukka",
    price: "₹200",
    category: ["non-vegetarian"],
    type: "Main Dish",
    desc: "A spicy, flavorful mutton dish cooked with Indian spices. Great with rice or bread.",
  },
  {
    id: 16,
    imageName: "chai.jpg",
    name: "Chai",
    price: "₹20",
    category: ["vegetarian"],
    type: "Drinks",
    desc: "A refreshing drink made with tea leaves and milk, perfect for a mornings and evenings.",
  },
  {
    id: 17,
    imageName: "mangoJuice.jpg",
    name: "Mango Juice",
    price: "₹20",
    category: ["vegetarian"],
    type: "Drinks",
    desc: "A refreshing drink made with mangoes, perfect for a morning or evening.",
  },
  {
    id: 18,
    imageName: "guavaJuice.jpg",
    name: "Guava Juice",
    price: "₹20",
    category: ["vegetarian"],
    type: "Drinks",
    desc: "A refreshing drink made with guavas, perfect for a morning or evening.",
  },
  {
    id: 19,
    imageName: "chickenSoup.jpg",
    name: "Chicken Soup",
    price: "₹320",
    category: ["non-vegetarian"],
    type: "Drinks",
    desc: "A hearty soup made with chicken, perfect before a hearty meal.",
  },
  {
    id: 20,
    imageName: "muttonbone.jpg",
    name: "Mutton Bone Soup",
    price: "₹400",
    category: ["non-vegetarian"],
    type: "Drinks",
    desc: "A hearty soup made with mutton, perfect before a hearty meal.",
  },
];


export const articles = [
  {
    id: 1,
    title: "How to Cook Delicious Aloo Gobi",
    date: "January 3, 2023",
    Desc: "A traditional Indian dish made with potatoes and cauliflower, spiced with turmeric, cumin, and other flavorful ingredients. Perfect as a side or main dish.",
    imgSrc: "AlooGobi.jpg",
  },
  {
    id: 2,
    title: "Making the Perfect Bhel Puri at Home",
    date: "February 10, 2023",
    Desc: "A popular Indian street food, Bhel Puri is a delightful mixture of puffed rice, vegetables, and tamarind sauce. It's light, crunchy, and tangy.",
    imgSrc: "BhelPuri.jpg",
  },
  {
    id: 3,
    title: "How to Prepare Creamy Butter Chicken",
    date: "March 15, 2023",
    Desc: "A rich and creamy chicken dish cooked in tomato-based sauce, flavored with butter, cream, and a blend of traditional Indian spices.",
    imgSrc: "ButterChicken.jpg",
  },
  {
    id: 4,
    title: "Refreshing Buttermilk: The Perfect Drink for Summers",
    date: "April 22, 2023",
    Desc: "A refreshing and tangy drink made from churned yogurt, commonly enjoyed to cool down on a hot day. Seasoned with cumin and herbs.",
    imgSrc: "Buttermilk.jpg",
  },
  {
    id: 5,
    title: "Chole Bhature: A Hearty Meal for Every Occasion",
    date: "May 30, 2023",
    Desc: "A North Indian classic dish consisting of spicy chickpeas (chole) served with deep-fried bread (bhature). It's a hearty and filling meal.",
    imgSrc: "CholeBhature.jpg",
  },
  {
    id: 6,
    title: "How to Make Traditional Dosa and Sambar",
    date: "June 18, 2023",
    Desc: "A crispy fermented rice pancake served with a side of spicy lentil soup (sambar), a favorite breakfast dish from South India.",
    imgSrc: "DosaSambar.jpg",
  },
  {
    id: 7,
    title: "Gourmet Burger: A Fusion of Indian and Western Flavors",
    date: "July 8, 2023",
    Desc: "A delicious fusion burger with a blend of Indian spices and traditional burger ingredients, offering the best of both worlds.",
    imgSrc: "GourmetBurger.jpg",
  },
  {
    id: 8,
    title: "Savoring Gulab Jamun: An Indian Dessert Delight",
    date: "August 5, 2023",
    Desc: "Soft, deep-fried dough balls soaked in sweet syrup, Gulab Jamun is a must-have dessert for any festive occasion.",
    imgSrc: "GulabJamun.jpg",
  },
  {
    id: 9,
    title: "Homemade Ice Cream: A Cool, Creamy Treat",
    date: "September 12, 2023",
    Desc: "A simple, homemade ice cream recipe made with natural ingredients. Creamy and delicious, it's a perfect dessert for all seasons.",
    imgSrc: "HomemadeIceCream.jpg",
  },
  {
    id: 10,
    title: "How to Make Authentic Homemade Samosas",
    date: "October 25, 2023",
    Desc: "Crispy and spicy, these homemade samosas are filled with a mixture of potatoes and peas, making them a favorite snack in India.",
    imgSrc: "HomemadeSamosas.jpg",
  },
  {
    id: 11,
    title: "The Best Indian Biryani Recipe",
    date: "November 14, 2023",
    Desc: "A fragrant rice dish made with basmati rice, spices, and meat or vegetables. Biryani is known for its rich aroma and delicious taste.",
    imgSrc: "IndianBiryani.jpg",
  },
  {
    id: 12,
    title: "A Guide to Traditional Indian Meals",
    date: "December 1, 2023",
    Desc: "A wholesome Indian thali with a variety of dishes including curries, rice, and bread, representing the rich culinary diversity of India.",
    imgSrc: "IndianMeals.jpeg",
  },
  {
    id: 13,
    title: "Making Soft and Delicious Indian Parathas",
    date: "January 3, 2024",
    Desc: "A flatbread that's a staple in Indian households, parathas can be stuffed with various fillings like potatoes or paneer for extra flavor.",
    imgSrc: "IndianParathas.jpg",
  },
  {
    id: 14,
    title: "Indian Pulao: A Simple and Flavorful Rice Dish",
    date: "February 10, 2024",
    Desc: "A one-pot rice dish cooked with vegetables, aromatic spices, and herbs, Pulao is a lighter version of biryani but equally delicious.",
    imgSrc: "IndianPulao.jpg",
  },
  {
    id: 15,
    title: "Comforting Kichdi: A Simple and Nutritious Meal",
    date: "March 18, 2024",
    Desc: "A traditional Indian comfort food made with rice and lentils, cooked together with minimal spices for a simple and wholesome dish.",
    imgSrc: "Kichdi.jpeg",
  },
  {
    id: 16,
    title: "How to Make Fresh Mango Lassi",
    date: "April 25, 2024",
    Desc: "A refreshing mango and yogurt-based drink that combines the sweetness of ripe mangoes with the tanginess of yogurt.",
    imgSrc: "MangoLassi.jpg",
  },
  {
    id: 17,
    title: "Creamy and Savory Meat Stroganoff Recipe",
    date: "May 7, 2024",
    Desc: "A rich and creamy meat dish made with sautéed pieces of beef, mushrooms, and sour cream. Perfect for a comforting meal.",
    imgSrc: "MeatStroganoff.jpg",
  },
  {
    id: 18,
    title: "Classic Paneer Butter Masala Recipe",
    date: "June 15, 2024",
    Desc: "Paneer Butter Masala is a rich and creamy curry made with paneer, tomato gravy, and butter. It's a popular vegetarian dish.",
    imgSrc: "PaneerButterMasala.jpg",
  },
  {
    id: 19,
    title: "The Perfect Pizza Dough Recipe",
    date: "July 22, 2024",
    Desc: "Learn how to make soft, elastic pizza dough from scratch, perfect for making your favorite homemade pizza.",
    imgSrc: "PizzaDough.jpg",
  },
  {
    id: 20,
    title: "How to Make Hearty Rajma",
    date: "August 9, 2024",
    Desc: "Rajma is a popular North Indian dish made with red kidney beans simmered in a flavorful tomato-based gravy.",
    imgSrc: "Rajma.jpg",
  },
  {
    id: 21,
    title: "Rava Cake: A Delicious Indian Dessert",
    date: "September 15, 2024",
    Desc: "A soft and spongy cake made with semolina (rava), flavored with coconut or cardamom. Perfect for tea-time.",
    imgSrc: "RavaCake.jpg",
  },
  {
    id: 22,
    title: "Healthy Summer Salads with a Twist",
    date: "October 21, 2024",
    Desc: "A variety of fresh and vibrant summer salads, using seasonal ingredients and a touch of Indian spices for a flavorful meal.",
    imgSrc: "SummerSalads.jpg",
  },
  {
    id: 23,
    title: "How to Make Mumbai's Famous Vada Pav",
    date: "November 3, 2024",
    Desc: "A popular street food from Mumbai, Vada Pav is a spicy potato fritter served in a bun with chutneys. It's often referred to as the Indian burger.",
    imgSrc: "VadaPav.jpg",
  },
];


export const months = [
  "January", "February", "March", "April", "May", "June", 
  "July", "August", "September", "October", "November", "December"
];

export const years = [
  "2023", "2024"
];


